### ISSUE TITLE
problem with dlnacast

### ISSUE THREAD

**Issue by pastynko** [ManRueda/renderer-finder#3]
Hello,

I'm trying to get dlnacast working but I'm getting these errors.

dlnacast --listRenderer

osmc@osmc:~$ dlnacast --listRenderer
events.js:142
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read property 'root' of undefined
    at /usr/lib/node_modules/dlnacast/node_modules/renderer-finder/src/RendererFinder.js:42:22
    at Parser.<anonymous> (/usr/lib/node_modules/dlnacast/node_modules/xml2js/lib/xml2js.js:487:18)
    at emitOne (events.js:78:13)
    at Parser.emit (events.js:170:7)
    at Object.onerror (/usr/lib/node_modules/dlnacast/node_modules/xml2js/lib/xml2js.js:308:26)
    at emit (/usr/lib/node_modules/dlnacast/node_modules/sax/lib/sax.js:639:35)
    at error (/usr/lib/node_modules/dlnacast/node_modules/sax/lib/sax.js:668:5)
    at strictFail (/usr/lib/node_modules/dlnacast/node_modules/sax/lib/sax.js:692:7)
    at closeTag (/usr/lib/node_modules/dlnacast/node_modules/sax/lib/sax.js:885:9)
    at Object.write (/usr/lib/node_modules/dlnacast/node_modules/sax/lib/sax.js:1436:13)

and dlnacast --address ipaddress /path/to/file

osmc@osmc:~$ dlnacast --address 192.168.2.86 /home/osmc/test/test4.mp4
_http_client.js:27
      throw new Error('Unable to determine the domain name');
      ^
Error: Unable to determine the domain name
    at new ClientRequest (_http_client.js:27:13)
    at Object.exports.request (http.js:32:10)
    at Object.exports.get (http.js:36:21)
    at fetch (/usr/lib/node_modules/dlnacast/node_modules/upnp-mediarenderer-client/node_modules/upnp-device-client/index.js:549:18)
    at MediaRendererClient.DeviceClient.getDeviceDescription (/usr/lib/node_modules/dlnacast/node_modules/upnp-mediarenderer-client/node_modules/upnp-device-client/index.js:44:3)
    at MediaRendererClient.DeviceClient.getServiceDescription (/usr/lib/node_modules/dlnacast/node_modules/upnp-mediarenderer-client/node_modules/upnp-device-client/index.js:58:8)
    at MediaRendererClient.DeviceClient.callAction (/usr/lib/node_modules/dlnacast/node_modules/upnp-mediarenderer-client/node_modules/upnp-device-client/index.js:88:8)
    at MediaRendererClient.load (/usr/lib/node_modules/dlnacast/node_modules/upnp-mediarenderer-client/index.js:119:8)
    at runDLNA (/usr/lib/node_modules/dlnacast/index.js:123:13)
    at /usr/lib/node_modules/dlnacast/index.js:111:11

My node.js version is 5.2.0 and version of npm is 3.5.2
Any idea where should be the problem?

Thanks!

**Comment by manrueda** [comment]
I just release a new version with a correct error handling.

This maybe don't fix the error, because the error was when trying to catch an error.

I will close this issue and if anything comes up, create a new one.
